### ISSUE TITLE
OS X install instructions need a small change

### ISSUE THREAD

**Issue by sg-s** [arialdomartini/oh-my-git#36]
instead of 

```
cd ~ && git clone https://github.com/arialdomartini/oh-my-git.git && echo source $HOME/oh-my-git/prompt.sh >> .profile
```
(which didn't work) I had to 

```
cd ~ && git clone https://github.com/arialdomartini/oh-my-git.git && echo source $HOME/oh-my-git/prompt.sh >> **.bash_profile**
```

**Comment by arialdomartini** [comment]
Hi @sg-s 
Well, the thing is a bit more complicated.

When you run a terminal, what you get is a login session, so bash will source  ```~/.bash_profile``` or ```~/.profile```

Yet, when you run a new bash inside a bash, ```.bashrc``` is sourced, and the profile files are skipped.

Look: I put a ```echo I'm bash profile``` inside ```~/.bash_profile``` and ```echo I'm bashrc``` inside ```~/.bashrc```. This is what I get when I open a new terminal and then I run a bash inside a bash:

![screen shot 2015-01-21 at 07 14 51](https://cloud.githubusercontent.com/assets/150719/5831966/3bc1f85e-a13d-11e4-804d-9d52cb97a06f.png)

Now, there's a complication: if there's no ```~/.bash_profile```, bash would look for a ```~/.profile``` file. If there's a ```~/.bash_profile```, then ```.profile``` is ignored.

Using ```~/.profile``` is a bit easier, since it is used both by bash and zsh (and other shells, I suppose, but I didn't try).

So, I guess that in your case a ```.bash_profile``` was already present, and this could explain why oh-my-git startup command in ```.profile``` was ignored. I'm going to document this in the ```README.md``` file

**Comment by sg-s** [comment]
thanks, i learnt something!
i found this in my `.bash_profile`
```
case $- in
   *i*) source ~/.bashrc
esac
```

**Comment by arialdomartini** [comment]
I didn't no either! Nice to know.
Cheers!
