### ISSUE TITLE
need help installing fonts

### ISSUE THREAD

**Issue by sg-s** [arialdomartini/oh-my-git#37]
1. Do I download both the .sh and the .ttf files from [here](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched)?
1.1: Is there a simple way to download them? Cloning the repo only seems to get the master branch, not the branch with "patched"
2. Where do I put them? I take it I shouldn't install the fonts using OS X's font book?
3. I tried following instructions [here](https://github.com/gabrielelana/awesome-terminal-fonts) but nothing works.

**Comment by arialdomartini** [comment]
Hi @sg-s 

1 - Well, only the ```.ttf``` files are required in order to install the fonts. You can download them in several different ways. Just browse to https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched and download the ```.ttf``` files; or run

```
cd /tmp
git clone https://github.com/gabrielelana/awesome-terminal-fonts.git
cd awesome-terminal-fonts
git checkout patching-strategy
cd patched
open .
```
(as you see, when you clone a repo, all branches are cloned)

Or, you can download the zipped version of the repo, at the specific branch, from here https://github.com/gabrielelana/awesome-terminal-fonts/archive/patching-strategy.zip


2 - You don't need to copy the fonts. Just open them in Font Book (double clicking on their icons), then click on the button ```Install font``` in the right bottom of the window
![screen shot 2015-01-21 at 08 25 27](https://cloud.githubusercontent.com/assets/150719/5832531/1c56e98e-a147-11e4-9233-908c8b4322ee.png)
3 -  I hope this helped.

**Comment by arialdomartini** [comment]
I added more detailed instructions to the readme. I hope this helps.

**Comment by zedtux** [comment]
I have the first described issue from the Troubleshooting section of the README.

I have installed `antigen` with `zsh`, I have updated my `.zshrc` file accordingly and I start to see the prompt but with the font issue (having crosses instead of icons).
I have downloaded the `.ttf` files, clicked the `Install Font` button and updated the iterm2 configuration in order to use the `Droid Sans Mono Awesome` font.

What did I do wrong ?

**Comment by zedtux** [comment]
Ha ! I've found !

iterm2 has 2 font fields: `Regular font` and `Non-ASCII Font`. I had updated only the first one. Updating the second one make it working.

**Comment by sg-s** [comment]
@arialdomartini thanks!
the crucial step I forgot to do was this:
![screen shot 2015-01-21 at 11 36 43 am](https://cloud.githubusercontent.com/assets/6005346/5840236/0483a91c-a162-11e4-9416-06f85ae4c296.png)

**Comment by arialdomartini** [comment]
Nice! Enjoy, and thanks!

**Comment by Serhioromano** [comment]
@zedtux Thanks. I totally forgot to change fonts in new iTerm 3. there are profiles now. I spent half of the day in attempt to see icons instead of crosses. I broke my brew, restored when I only need to change font parameter in iTerm options.
