### ISSUE TITLE
Resized First part of git prompt

### ISSUE THREAD

**Issue by adiultra** [arialdomartini/oh-my-git#91]
Is there a way for the first part of the git command to resize as new symbols appear later?

![selection_005](https://cloud.githubusercontent.com/assets/12121575/13501483/e1168e92-e18c-11e5-8332-ada405064031.png)

In the above screen shot I don't like that the blue coloured first part is that huge, I just want it to be four chars, when no special thing is available.

Can I do That. If not, Can it be a new feature?

**Comment by arialdomartini** [comment]
ciao @adiultra 

Yes, it can be a new feature as soon as I'll implement the support for custom themes in omg.
So far, this is intentional: when I started omg the original idea was to provide the user with a sort of dashboard, a bar with led icons, which could be off or on, depending on same states, just like in the instrumental panel of a car; in other words, I liked the idea my eyes could get used to an absolute position of the screen being dedicated to a specific information.

Of course, by editing omg you will be easily able to change this behaviour. The line where omg replaces a missing symbol with a space is [this one](https://github.com/arialdomartini/oh-my-git/blob/master/prompt.sh#L40). I did not tried, but I'm pretty confident that by replacing that space with `''` you will get what you wish.

I'd pay to be able to work on omg and add support for custom themes, but unfortunately I'm struggling to find the time...
